config/routes.rb
Theredarrowgallery::Application.routes.draw do

  root :to => 'home#index'
  
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :artists
  resources :exhibitions
  resources :contact_infos, :path => 'contact'
  resources :about_infos, :path => 'about'
  resources :history_infos, :path => 'history'
  resources :mailing_list_contacts
  resources :exclusive
  resources :home

end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
      if user && user.role == "admin"
        can :access, :rails_admin
        can :dashboard
        can :manage, :all
      elsif user && user.role == "artist"
        can :access, :rails_admin
        can :dashboard
        can [:read, :update], Artist, :live => true, :user_id => user.id
        can :manage, ArtistImage, :artist => { :user_id => user.id }
      elsif user && user.role == "client"
        cannot :access, :rails_admin
        cannot :dashboard
        can :read, ClientImage, :live => true, :user_id => user.id
      else      
        cannot :access, :rails_admin
        cannot :dashboard
        can :read, AboutInfo
        can :read, Announcement
        can :read, Artist
        can :read, ArtistImage
        can :read, ContactInfo
        can :read, Exhibition
        can :read, ExhibitionImage
        can :read, SlideshowImage
     end
   end

end

app/models/about_info.rb
class AboutInfo < ActiveRecord::Base
  attr_accessible :body, :title, :live, :info_order, :image, :image_cache, :remove_image

  mount_uploader :image, AboutInfoImageUploader

  scope :live_and_ordered, :conditions => 'live IS TRUE', :order => :info_order
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :end_date, :link_target, :live, :start_date, :text

  scope :current, :conditions => ["live IS TRUE AND ? between start_date AND end_date", Date.today]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :artist_images
  belongs_to :user

  attr_accessible :name, :live, :statement, :cv, :cv_cache, :remove_cv, :press, :press_cache, :remove_press,
                  :user_id, :artist_image_ids, :artist_images_attributes, :allow_destroy => true

  accepts_nested_attributes_for :artist_images, :allow_destroy => true

  mount_uploader :cv, PdfUploader
  mount_uploader :press, PdfUploader

  scope :live, :conditions => "live IS TRUE"
end

app/models/artist_image.rb
class ArtistImage < ActiveRecord::Base
  belongs_to :artist

  attr_accessible :image, :image_cache, :remove_image, :artist_id, :dimensions, 
                  :media, :title, :year, :thumbnail_order

  mount_uploader :image, WorkShowcaseImageUploader

  scope :ordered, :order => "thumbnail_order ASC"
end

app/models/client_image.rb
class ClientImage < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :artist, :comment, :dimensions, :media, :title, :view_order, :year, :user_id, :live,
                  :image, :image_cache, :remove_image
                  
  mount_uploader :image, ClientImageUploader
  
  scope :live, :conditions => "live IS TRUE"
  scope :ordered, :order => "view_order ASC"
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
  attr_accessible :body, :title, :live, :info_order

  scope :live, :conditions => 'live IS TRUE', :order => "info_order ASC"
end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
  has_many :exhibition_images

  attr_accessible :artists, :closing, :description, :opening, :reception_date, :reception_end_time, :title, :live, 
                  :press_release, :press_release_cache, :remove_press_release, :poster, :poster_cache, :remove_poster,
                  :exhibition_image_ids, :exhibition_images_attributes, :allow_destroy => true

  accepts_nested_attributes_for :exhibition_images, :allow_destroy => true

  scope :chronological, :conditions => "live IS TRUE", :order => "opening DESC"

  mount_uploader :press_release, PdfUploader
  mount_uploader :poster, PdfUploader
end

app/models/exhibition_image.rb
class ExhibitionImage < ActiveRecord::Base
  belongs_to :exhibition

  attr_accessible :image, :image_cache, :remove_image, :exhibition_id, :artist,
                  :title, :year, :media, :dimensions, :thumbnail_order
    
  mount_uploader :image, WorkShowcaseImageUploader

  scope :ordered, :order => "thumbnail_order ASC"
end

app/models/mailing_list_contact.rb
class MailingListContact < ActiveRecord::Base
  attr_accessible :email

  validates :email, :presence => true, 
                    :uniqueness => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
end

app/models/slideshow_image.rb
class SlideshowImage < ActiveRecord::Base
  attr_accessible :image, :image_cache, :remove_image, :live, :caption
  
  mount_uploader :image, SlideshowImageUploader

  scope :live, :conditions => "live IS TRUE"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :role

  ROLES = %w[admin client artist]

  def role_enum
     [['Admin', 'admin'], ['Client', 'client'], ['Artist', 'artist']]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  protect_from_forgery
  
  def index
    @artists = Artist.live.shuffle
  end
end

app/controllers/exclusive_controller.rb
class ExclusiveController < ApplicationController
  protect_from_forgery
  
  def index
    if user_signed_in?
      @images = ClientImage.where(:user_id => current_user.id).live.ordered
    else 
      redirect_to new_user_session_path, :alert => "Please sign in to view exclusive content."
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery  
  
  def index
    @slideshow_images = SlideshowImage.live.shuffle
  end
end

app/helpers/about_infos_helper.rb
module AboutInfosHelper
  
  def get_header_snippet
    @about_infos.first
  end
  
  def break_snippets_into_two_columns
    left_hand_info = []
  	@about_infos.each_with_index { |info, index| left_hand_info << info if index.odd? }
  	right_hand_info = @about_infos - left_hand_info
    right_hand_info.shift # Remove the first element, we show the first snippet as the header
  	[left_hand_info, right_hand_info]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_announcement
    Announcement.current.first
  end

  def users_first_name
    current_user.name.split[0...1].first if user_signed_in? && !current_user.name.nil?
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  
  # If we are on the artists page, we don't show the artist name again in the label.
  def get_artist_name artist_image
    artist_image.artist.name
  end
  
end

app/helpers/exclusive_helper.rb
module ExclusiveHelper
  
  # If we are on the artists page, we don't show the artist name again in the label.
  def get_artist_name client_image
    client_image.artist
  end
  
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper

  def get_artist_name exhibition_image
    exhibition_image.artist
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Red Arrow Art Gallery </title>

  <%= favicon_link_tag '/assets/favicon.ico' %>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag 	 "http://fonts.googleapis.com/css?family=Poiret+One", :media => "all" %>

  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>

</head>
<body>
	<% if flash[:notice] %>
		<div class="flash_notice"><%= flash[:notice] %></div>
	<% end %>
	<% if flash[:error] %>
		<div class="flash_error"><%= flash[:error] %></div>
	<% end %>
	<% if flash[:alert] %>
		<div class="flash_error"><%= flash[:alert] %></div>
	<% end %>

	<%= render "shared/navigation_and_logo" %>

	<div id="port">
		<%= yield %>
	</div>

	<%= render "shared/gallery_information_footer" %>

</body>
</html>

app/views/shared/_gallery_information_footer.html.erb
<% if !current_announcement.nil? %>
	<div id="announcement">
		<span id="ascii_arrow">&#45;&gt;</span>
		<%= link_to current_announcement.text, current_announcement.link_target %>
	</div>
<% end %>

<div id="information">
	<span class="info_snippet">THE&nbsp;RED&nbsp;ARROW&nbsp;GALLERY</span>
	<span class="info_snippet">61597&nbsp;29&nbsp;PALMS&nbsp;HWY,<span>
	<span class="info_snippet">JOSHUA&nbsp;TREE,&nbsp;CA&nbsp;92252</span>
	<span class="info_snippet">info@theredarrowgallery.com</span>
</div>

app/views/shared/_info_snippet.html.erb
<p>
	<div class="title"><%= info.title %></div>
	<%= image_tag info.image.compact, :class => "info_snippet_image" unless info.image.blank? %>
	<%= simple_format info.body %>
</p>

app/views/shared/_label.html.erb
<span class="label">
	<%= get_artist_name showcase_image %><br />
	<span class="work_title"><%= showcase_image.title %></span>, 
	<%= showcase_image.year %><br />
	<%= showcase_image.media %><br />
	<%= showcase_image.dimensions %>
</span>

app/views/shared/_navigation_and_logo.html.erb
<div id="logo">
	<%= image_tag "red_arrow_logo.png" %>
</div>

<div id="nav">
	<%= link_to "HOME", root_url, :class => controller.class == HomeController ? "nav_button current" : "nav_button" %>
	<%= link_to "EXHIBITIONS", exhibitions_path, :class => controller.class == ExhibitionsController ? "nav_button current" : "nav_button" %>
	<%= link_to "ARTISTS", artists_path, :class => controller.class == ArtistsController ? "nav_button current" : "nav_button" %>
	<%= link_to "CONTACT", contact_infos_path, :class => controller.class == ContactInfosController ? "nav_button current" : "nav_button" %>
	<%= link_to "ABOUT", about_infos_path, :class => controller.class == AboutInfosController ? "nav_button current" : "nav_button" %>
	<% if user_signed_in? %>
	  <%= link_to "Logout #{users_first_name}", destroy_user_session_path, :method => :delete, :id => "sign_out_button" %>
	<% end %>
</div>

app/views/shared/_showcase_image.html.erb
<div class="work">
	<div class="work_centering">
		<%= image_tag showcase_image.image.full_size,
		 	:class => "full_size",
			:alt => [get_artist_name(showcase_image), showcase_image.title,
					showcase_image.year.to_s, showcase_image.media,
					showcase_image.dimensions].join(" - ") %>
	</div>				
</div>

app/views/shared/_thumbnails.html.erb
<div class="thumbnails">
	<% showcase_images.each do |showcase_image| %>
			<%= link_to image_tag(showcase_image.image.thumbnail, 
				:class => "thumbnail", 
				:alt => [get_artist_name(showcase_image), showcase_image.title,
						showcase_image.year.to_s, showcase_image.media,
						showcase_image.dimensions].join(" - "),
				:data => {"image" => showcase_image}),
				showcase_image.image.full_size.url %>
	<% end %>
</div>